name: Learning GitHub Actions
run-name: ${{ github.actor }} trying actions

on:
  push:
    branches: ["develop", "main"] # where the pipeline will be triggered

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v5
      
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

  verificate:
    needs: explore-github-actions # only executes if explore-github-actions pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: './'
          css: false
          format: json
          # blacklist: 'node_modules/**' # ignore files or folders

      - name: Save error logs
        if: failure() # Only runs if the previous step fails, not if some error is found, but if the action itself fails
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-validacao
          path: html5validator.log # Log file generated by HTML5Validator

  fake_deploy:
    needs: verificate # onlye executes if vericiate pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only executes on main branch
    steps:
      - name: Fake Deploy
        run: echo "Deploying to production environment..."

